version: '3.4'
services:
  web:
    command: ./bin/run-dev.sh
    image: mozmeao/nucleus:${GIT_COMMIT_SHORT:-latest}
    env_file:
      - .env
      - docker/envfiles/dev.env
    build:
      context: .
      args:
        GIT_SHA: ${GIT_COMMIT:-latest}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  worker:
    command: ./bin/run-worker.sh
    image: mozmeao/nucleus:${GIT_COMMIT_SHORT:-latest}
    env_file:
      - .env
      - docker/envfiles/dev.env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  test:
    image: mozmeao/nucleus:${GIT_COMMIT_SHORT:-latest}
    command: ./bin/run-tests.sh
    env_file:
      - docker/envfiles/dev.env
      - docker/envfiles/test.env
    volumes:
      - .:/app
    depends_on:
      - db

  test-image:
    image: mozmeao/nucleus:${GIT_COMMIT_SHORT:-latest}
    command: ./bin/run-tests.sh
    env_file:
      - docker/envfiles/dev.env
      - docker/envfiles/test.env
    depends_on:
      - db

  db:
    image: postgres:12.8-alpine
    environment:
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis

  builder:
    image: mozmeao/nucleus:builder-${GIT_COMMIT_SHORT:-latest}
    build:
      context: .
      target: builder
